spring:
  application:
    name: nakitera-case-study
  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  messages:
    basename: exceptionMessages, validationMessages, responseMessages
    encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
server:
  port: 8080

