CREATE TABLE asset
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT,
    asset_name  VARCHAR(255)                            NOT NULL,
    size        INT                                     NOT NULL,
    usable_size INT                                     NOT NULL,
    CONSTRAINT pk_asset PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id  BIGINT,
    asset_name   VARCHAR(255)                            NOT NULL,
    size         INT                                     NOT NULL,
    price        INT                                     NOT NULL,
    order_side   VARCHAR(255)                            NOT NULL,
    order_status VARCHAR(255)                            NOT NULL,
    create_date  TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    role        VARCHAR(255)                            NOT NULL,
    customer_id BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE asset
    ADD CONSTRAINT uc_1161d77c7251e6d74e4a1e569 UNIQUE (customer_id, asset_name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_customer UNIQUE (customer_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE asset
    ADD CONSTRAINT FK_ASSET_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);